FROM node:18-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
COPY ../shared /shared
RUN npm ci

# Copy source code
COPY . .

# Expose port
EXPOSE 3000

# Start the application
CMD ["npm", "run", "dev"]

